### ISSUE TITLE
Add popular CRDs

### ISSUE THREAD

**Issue by luisdavim** [yannh/kubernetes-json-schema#10]
Hi,

would it be possible to include the schemas for popular CRDs such as the Pormetheus Operator ones, Flagger's Canary, etc... ?

Thanks.

**Comment by luisdavim** [comment]
Maybe this could help? https://gist.github.com/rawc0der/040670cd69c4132f7d6aeb56f6668048

**Comment by eyarz** [comment]
@luisdavim the script in your link is not working.
Kubeconform already has a similar script to extract schemas and convert them into JSON files:
https://github.com/yannh/kubeconform/blob/master/scripts/openapi2jsonschema.py

**Comment by luisdavim** [comment]
I didn't try the script yet, but I think you'd need both, one to extract the openapi schema from the CRD manifest and the other to convert it to a JSON schema.

**Comment by yannh** [comment]
Hello :wave:  Adding non-core manifests to this repo is out of scope, but using the tooling @eyarz pointed out you should easily be able to convert CRDs to JSON and use them for validation. See documentation here: https://github.com/yannh/kubeconform/#overriding-schemas-location---crd-and-openshift-support
