### ISSUE TITLE
No schemas exist for kustomization.yaml

### ISSUE THREAD

**Issue by DevonBT** [yannh/kubernetes-json-schema#13]
This issue existed in the original repo from instrumenta (see https://github.com/instrumenta/kubernetes-json-schema/issues/9):

> Kubeval fails for any kustomization.yaml file as no schema is included for it.
> As https://kustomize.io/ v2.0 is merged into kubectl since 1.14., it would be superb to include the schema here.
> (Yeah, I know this is a moving target as it changed with newer releases of Kustomize)

**Comment by eyarz** [comment]
I wonder if this is the correct behavior...?
Just like this project doesn't hold the schema definition for Helm chart or values, I don't think it should do it for kustomize.
If someone wants to verify his K8s schema with kustomize, he can just build the manifest and pipe it to kubeconform.

BTW, you can validate the kustomization.yaml file itself with [this project](https://github.com/python-jsonschema/jsonschema) and the schema from the [schema-store](http://json.schemastore.org/kustomization):
`$ jsonschema --instance sample.json sample.schema`

**Comment by yannh** [comment]
Hi @DevonBT ! I have no immediate plans to support kustomize - this repo solely contains the files from the Kubernetes swagger file https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json  converted to json schemas! I hope @eyarz recommendation helped :bow:

**Comment by gecube** [comment]
the same. Otherwise it is impossible to check the manifests build with kustomize.
