### ISSUE TITLE
ClusterIssuer add 

### ISSUE THREAD

**Issue by xxxvik-xakerxxx** [yannh/kubernetes-json-schema#16]
please add validation on ClusterIssuer to schemas
ClusterIssuer letsencrypt-staging failed validation: could not find schema for ClusterIssuer

**Comment by eyarz** [comment]
ClusterIssuer is not a native K8s object (it's a CustomResource), so it's not part of the K8s schema and therefore won't be added to this project.

**So what can you do instead?**
You can wait until this CustomResource is [added to the CRDs-catalog](https://github.com/datreeio/CRDs-catalog/issues/40), and then it will also be supported by Kubeconform, or you can use the [CRD Extractor](https://github.com/datreeio/CRDs-catalog#crd-extractor)* and pass the output to Kubeconform.

*if you are using the CRD Extractor, it would be great if you could also open a PR and add it to the CRDs-catalog. This way, the rest of the community will also be able to use this schema for validation :)

**Comment by yannh** [comment]
Pretty much what @eyarz said :) Closing this ticket as out of scope for this repo, maybe I could add documentation to explicitly mention how to use CRDs-catalog in Kubeconform.
