### ISSUE TITLE
Provide schemas for each latest minor version

### ISSUE THREAD

**Issue by ste93cry** [yannh/kubernetes-json-schema#17]
Right now all the schemas are organized based on the patch version. I would like to validate the input against the latest patch version, no matter what it is, but there is no easy way to do it. What do you think about providing the schemas categorized by minor version too? As an example of what I mean, I would love to see:

- `v1.x-local`
- `v1.x-standalone-strict`
- `v1.x-standalone`
- `v1.x`

**Comment by eyarz** [comment]
>  I would like to validate the input against the latest patch version

I guess you mean minor, not patch 😅

I think solving it via code/script on the user or Kubeconform CLI side will make more sense than creating duplicate schemas on this repo. That's my 2c.

**Comment by ste93cry** [comment]
To do it I imagine that I should fetch the list of tags from the Kubernetes repo, find the latest minor version, then the latest patch version of that minor and finally use `kubeval` to validate the input against it. Considering that the first part of this process is what the script used to update this repo does, it sounds like it is something that should live here rather than on the user side.

**Comment by eyarz** [comment]
🤔
You can use the [github API ](https://docs.github.com/en/rest/repos/contents#about-the-repository-contents-api)to list all the dirs in the repo and pick the major dir to use with Kubeconform (e.g. `x.y.0`).

**Comment by ste93cry** [comment]
Whatever way to get the greatest version, I still don't understand why it should not work out-of-the-box to just point the schema location to this repository and expect it to just work like it does for patches. I think it would be a lot more common to validate against the minor version rather than against the patch, or not?

**Comment by eyarz** [comment]
Maybe there is confusion between what you're looking for and what I'm answering 😅
Are you asking to add to this repo a new dir that will be called `1.x` and will contain the schemas for `1.x.0`?

**Comment by ste93cry** [comment]
I'm asking to add a new dir called `1.x` that will point to the latest patch release of that minor version. I think it would be useful to validate the input against the minor version of Kubernetes rather than against its patch version, as I don't expect changes to be done to the schemas between patches.

**Comment by eyarz** [comment]
Got it.
Thank you for the clarification :)

**Comment by yannh** [comment]
Mhhhh, if this is solvable with symlinks (really not sure) then we could probably do that. Otherwise it would likely bloat this repo even more... Would definitely consider merging a patch should someone propose one!

**Comment by ste93cry** [comment]
I did some testing, and although generating the symlinked folders is quite simple, neither `kubeval` nor `kubeconform` works as expected because GitHub does not follow the symlink when accessing the schema 😢 

> it would likely bloat this repo even more

I agree that there would be even more bloat, but I think it would be for a good reason. Anyway, as there isn't apparently any way to make it working, feel free to close this issue if you don't want to reconsider adding the missing bits.

**Comment by eyarz** [comment]
@ste93cry maybe if you will open an issue/PR in the **kubernetes-validate** project, it will make more sense for your use case because this project contains [only majors for each K8s version](https://github.com/willthames/kubernetes-validate/tree/main/src/kubernetes_validate/kubernetes-json-schema).

**Comment by yannh** [comment]
Yep, I think a point can be made that the schemas do change very little between patch versions... if you validate against the right minor version that most likely should be enough :thinking:

**Comment by yannh** [comment]
Closing this as wontfix - I'd recommend to just use the .0 patch version for each version of Kubernetes in the meantime, if you don't want to update this every time - the variations should be minimal.
