### ISSUE TITLE
HorizontalPodAutoscaler v2beta2 is not available

### ISSUE THREAD

**Issue by jmluy** [yannh/kubernetes-json-schema#18]
The commit from dfb08927cf removed the definition for HorizontalPodAutoscaler v2beta2. Shouldn't this be available up to 1.25?

**Comment by syossan27** [comment]
@yannh 
I am currently using v1.23 with GKE and would be very annoyed if autoscaling/v2beta2 is not available.
Can you do something about this? Any help would be appreciated.

**Comment by yannh** [comment]
Updated in master, yes -  master points to the master branch in the Kubernetes repo. Please ensure you select your version of Kubernetes (in kubeval/kubeconform) and all should be good. 

![image](https://user-images.githubusercontent.com/210669/186851089-e90fbb62-0ae0-49fc-ac5b-72d9aaef2da7.png)
