### ISSUE TITLE
Recommendation for partial download or partial checkout

### ISSUE THREAD

**Issue by yabberyabber** [yannh/kubernetes-json-schema#24]
A shallow clone of the repo is 19GB. I end up using a workflow like this locally so that I don't have to download/cachethe entire 19GB of content -

```bash
git clone --depth 1 --filter=blob:none --sparse https://github.com/yannh/kubernetes-json-schema
cd kubernetes-json-schema
git sparse-checkout set "${K8S_VERSION}-standalone-strict"
```
That fetches only the subdirectory associated with the version of kubernetes that I want to validate against.

Is there a better way to do this? I'm definitely avoiding the vast majority of the download, but it still seems I'm downloading a rather large index file. It seems like some combination of `git archive` and the github API may allow me to skip fetching the git indexes.

If the answer is "no", that's totally fine. I am certainly getting a lot of usage out of the repo as-is. Thanks for maintaining this project!

**Comment by yannh** [comment]
Hi @yabberyabber , yes - this repo is unfortunately pretty large. The answer is - you might have to fiddle with git and/or Github - I am not sure what the best way would be, but please feel free to update this ticket should you find a reasonable way! 
Best, Yann
