### ISSUE TITLE
v1.15-v1.18 are deleted

### ISSUE THREAD

**Issue by ns-kliu** [yannh/kubernetes-json-schema#27]
Hello @yannh , could you explain why deleted v1.15-v1.18?

**Comment by yannh** [comment]
Hi @ns-kliu , the checkedout repo was too big and just checking it out was crashing the Github action runner. Do you still need them? if your use case is with kubeconform there might be an easy workaround i could document

**Comment by ns-kliu** [comment]
Yes, we leverage [datree](https://hub.datree.io/)

**Comment by yannh** [comment]
Technically older versions of the schemas are still in previous commits of this repo.

Kubernetes 1.15  manifests would still be in the commit 37b16fe3aa296c2388389102b1118fd89a7006f9  (which is just before I deleted them from the master branch). You would need to change the -schema-location you pass to kubeconform,  from -schema-location default , to  -schema-location 'https://raw.githubusercontent.com/yannh/kubernetes-json-schema/37b16fe3aa296c2388389102b1118fd89a7006f9/{{.NormalizedKubernetesVersion}}-standalone{{.StrictSuffix}}/{{.ResourceKind}}{{.KindSuffix}}.json'

I hope this helps solve your problem?

**Comment by yannh** [comment]
Related issue https://github.com/yannh/kubeconform/issues/233

**Comment by ns-kliu** [comment]
> Technically older versions of the schemas are still in previous commits of this repo.
> 
> Kubernetes 1.15 manifests would still be in the commit [37b16fe](https://github.com/yannh/kubernetes-json-schema/commit/37b16fe3aa296c2388389102b1118fd89a7006f9) (which is just before I deleted them from the master branch). You would need to change the -schema-location you pass to kubeconform, from -schema-location default , to -schema-location '[https://raw.githubusercontent.com/yannh/kubernetes-json-schema/37b16fe3aa296c2388389102b1118fd89a7006f9/{{.NormalizedKubernetesVersion}}-standalone{{.StrictSuffix}}/{{.ResourceKind}}{{.KindSuffix}}.json](https://raw.githubusercontent.com/yannh/kubernetes-json-schema/37b16fe3aa296c2388389102b1118fd89a7006f9/%7B%7B.NormalizedKubernetesVersion%7D%7D-standalone%7B%7B.StrictSuffix%7D%7D/%7B%7B.ResourceKind%7D%7D%7B%7B.KindSuffix%7D%7D.json)'
> 
> I hope this helps solve your problem?

Yes, it did solve my problem

**Comment by ns-kliu** [comment]
I think we need a tag `v1.15-v1.18` to point to the commit 37b16fe3aa296c2388389102b1118fd89a7006f9

**Comment by yannh** [comment]
Added the tag :+1:  thanks!

**Comment by viceice** [comment]
repo is again very big and some older eol versions should be removed
