### ISSUE TITLE
Kubevel --schema-location Flag Value

### ISSUE THREAD

**Issue by grifonas** [yannh/kubernetes-json-schema#3]
Hi Yann,
Thanks a lot for maintaining this.
Could you please give me a hint on what the `--schema-location` value for `kubeval` should be? 

I tried 
```kubeval --strict --ignore-missing-schemas --kubernetes-version v1.20.4 --schema-location https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/```

However for some reason `kubeval` gives a missing schema warning for all the K8S kinds. 

Thank you!

**Comment by grifonas** [comment]
Looks like my error was in putting the `v` prefix in front of the `--kubernetes-version` value.
Closing the issue.
Thank you!

**Comment by yannh** [comment]
Leaving open, how to use this repo with Kubeval & Kubeconform do absolutely belong in the Readme ;) Thanks for the report :+1:

**Comment by yannh** [comment]
Updated the Readme with a simple example :+1:
