### ISSUE TITLE
Missing schemas for K8s v1.29

### ISSUE THREAD

**Issue by stevehipwell** [yannh/kubernetes-json-schema#31]
The schemas for Kubernetes v1.29 haven't been generated yet but the stable Kubernetes version (_https://dl.k8s.io/release/stable.txt_) has been bumped so automation using this with `kubeconform` is currently erroring. Would it be possible to manually run the generate job to get the schemas updated?

BTW thanks for the work you do on this, it's a great tool!

**Comment by yannh** [comment]
They seem to be here now, the automation only runs every 2 days :+1:
