### ISSUE TITLE
Hosting the schemas parsed schemas in github is ill-advised [HTTP 429]

### ISSUE THREAD

**Issue by wrossmann** [yannh/kubernetes-json-schema#34]
One of my devs built k8s linting into the deployment pipeline, which broke this morning because this project had been rate-limited by github and we couldn't pull schemas or get our apps deployed.

Frankly, I agree with Github.

It's kind of bananas to have a 17GB repo that is essentially just a small shell script and a metric _boatload_ of build artifacts committed as code, and then treat githubusercontent as a free CDN for a largely cache-free downstream toolchain.

To get around this I've cannibalized your `build.sh` script into the below which simply generates a local copy that we can keep within our build system and eliminate a needless remote dependency.

```bash
#!/bin/bash -euo pipefail

SCHEMA_DIR=${SCHEMA_DIR:-${PWD}/k8s_schemas}
OPENAPI2JSONSCHEMABIN="docker run -i -v ${SCHEMA_DIR}:/out/schemas ghcr.io/yannh/openapi2jsonschema:latest"
K8S_VERSION="${1}"

function get_versions() {
    if [ -z "${K8S_VERSIONS}" ]; then
        K8S_VERSIONS=$(git ls-remote --refs --tags https://github.com/kubernetes/kubernetes.git | cut -d/ -f3 | grep -e '^v1\.[0-9]\{2\}\.[0-9]\{1,2\}$')
    fi
    echo "${K8S_VERSIONS}"
}

function check_version() {
    [ "$(get_versions | grep "^${1}\$")" = "${1}" ]
}

if [ -d "${SCHEMA_DIR}/${K8S_VERSION}" ]; then
    echo "Schema version dir already exists." >&2
    exit
fi

if ! check_version "${K8S_VERSION}"; then
    echo "k8s version ${K8S_VERSION} not found in upstream" >&2
  exit 1
fi

mkdir -p "${SCHEMA_DIR}"

SCHEMA="https://raw.githubusercontent.com/kubernetes/kubernetes/${K8S_VERSION}/api/openapi-spec/swagger.json"

$OPENAPI2JSONSCHEMABIN -o "schemas/${K8S_VERSION}" --expanded --kubernetes --stand-alone "${SCHEMA}"
$OPENAPI2JSONSCHEMABIN -o "schemas/${K8S_VERSION}" --kubernetes --stand-alone "${SCHEMA}"
```

Once this is done we just specify the schema URL as `file://${SCHEMA_DIR}/${K8S_VERSION}` and we're off to the races.

**Comment by yannh** [comment]
@wrossmann def. better to have the files locally, yep. I haven't experienced rate limits yet, there is a CDN in front of raw.githubusercontent.com  and I would expect a very high cache hit ratio. I do also wonder how heavy this exactly is - the index file is big but quite a bit less than a checkout.   Happy for alternatives :man_shrugging:
