### ISSUE TITLE
Invalid URL references in generated schemas

### ISSUE THREAD

**Issue by piotrminkina** [yannh/kubernetes-json-schema#6]
Hello,

Thanks for a great job :)

I noticed many generated JSON schemas are point to invalid URL. As an example https://github.com/yannh/kubernetes-json-schema/blob/acf735c510a74b7529f7811c3a8397ca8f43026b/v1.20.8/customresourcedefinition-apiextensions-v1beta1.json#L25 points to `https://kubernetesjsonschema.dev/...` instead of `https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/...`.

Once this problem has been corrected, it should become possible to validate CustomResourceDefinitions using swtich `-schema-location 'https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/{{ .NormalizedKubernetesVersion }}/{{ .ResourceKind }}{{ .KindSuffix }}.json'`. In my case works fine as below:

```
[...]
build/k8s/istio.custom.k8s.yaml - CustomResourceDefinition authorizationpolicies.security.istio.io is valid
build/k8s/istio.custom.k8s.yaml - CustomResourceDefinition envoyfilters.networking.istio.io is valid
build/k8s/istio.custom.k8s.yaml - CustomResourceDefinition istiooperators.install.istio.io is valid
[...]
```

Regards
Piotr Minkina

**Comment by yannh** [comment]
Hum nice catch I thought I had fixed this :thinking:  

What is the

**Comment by yannh** [comment]
@piotrminkina  fixed, somehow I really thought I did this in the past already! I would need to regenerate everything though :grimacing:  Do you need a particular version?

**Comment by piotrminkina** [comment]
Works as expected. Thanks!
